<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

/**
 * @property string $bo_table
 * @property string $bo_table
 * @property string $bo_table
 * @property string $bo_table
 * @property string $bo_table
 * @property string $bo_table
 * @property string $bo_table
 * @property string $bo_table
 * @property string $gr_id
 * @property string $bo_subject
 * @property string $bo_mobile_subject
 * @property string $bo_admin
 * @property string $bo_category_list
 * @property string $bo_skin
 * @property string $bo_mobile_skin
 * @property string $bo_include_head
 * @property string $bo_include_tail
 * @property string $bo_content_head
 * @property string $bo_mobile_content_head
 * @property string $bo_content_tail
 * @property string $bo_mobile_content_tail
 * @property string $bo_insert_content
 * @property string $bo_notice
 * @property string $bo_sort_field
 * @property string $bo_1_subj
 * @property string $bo_2_subj
 * @property string $bo_3_subj
 * @property string $bo_4_subj
 * @property string $bo_5_subj
 * @property string $bo_6_subj
 * @property string $bo_7_subj
 * @property string $bo_8_subj
 * @property string $bo_9_subj
 * @property string $bo_10_subj
 * @property string $bo_1
 * @property string $bo_2
 * @property string $bo_3
 * @property string $bo_4
 * @property string $bo_5
 * @property string $bo_6
 * @property string $bo_7
 * @property string $bo_8
 * @property string $bo_9
 * @property string $bo_10
 * @property string $gr_id
 * @property string $bo_subject
 * @property string $bo_mobile_subject
 * @property string $bo_admin
 * @property string $bo_category_list
 * @property string $bo_skin
 * @property string $bo_mobile_skin
 * @property string $bo_include_head
 * @property string $bo_include_tail
 * @property string $bo_content_head
 * @property string $bo_mobile_content_head
 * @property string $bo_content_tail
 * @property string $bo_mobile_content_tail
 * @property string $bo_insert_content
 * @property string $bo_notice
 * @property string $bo_sort_field
 * @property string $bo_1_subj
 * @property string $bo_2_subj
 * @property string $bo_3_subj
 * @property string $bo_4_subj
 * @property string $bo_5_subj
 * @property string $bo_6_subj
 * @property string $bo_7_subj
 * @property string $bo_8_subj
 * @property string $bo_9_subj
 * @property string $bo_10_subj
 * @property string $bo_1
 * @property string $bo_2
 * @property string $bo_3
 * @property string $bo_4
 * @property string $bo_5
 * @property string $bo_6
 * @property string $bo_7
 * @property string $bo_8
 * @property string $bo_9
 * @property string $bo_10
 * @property string $gr_id
 * @property string $bo_subject
 * @property string $bo_mobile_subject
 * @property string $bo_admin
 * @property string $bo_category_list
 * @property string $bo_select_editor
 * @property string $bo_skin
 * @property string $bo_mobile_skin
 * @property string $bo_include_head
 * @property string $bo_include_tail
 * @property string $bo_content_head
 * @property string $bo_mobile_content_head
 * @property string $bo_content_tail
 * @property string $bo_mobile_content_tail
 * @property string $bo_insert_content
 * @property string $bo_notice
 * @property string $bo_sort_field
 * @property string $bo_1_subj
 * @property string $bo_2_subj
 * @property string $bo_3_subj
 * @property string $bo_4_subj
 * @property string $bo_5_subj
 * @property string $bo_6_subj
 * @property string $bo_7_subj
 * @property string $bo_8_subj
 * @property string $bo_9_subj
 * @property string $bo_10_subj
 * @property string $bo_1
 * @property string $bo_2
 * @property string $bo_3
 * @property string $bo_4
 * @property string $bo_5
 * @property string $bo_6
 * @property string $bo_7
 * @property string $bo_8
 * @property string $bo_9
 * @property string $bo_10
 * @property string $gr_id
 * @property string $bo_subject
 * @property string $bo_mobile_subject
 * @property string $bo_admin
 * @property string $bo_category_list
 * @property string $bo_select_editor
 * @property string $bo_skin
 * @property string $bo_mobile_skin
 * @property string $bo_include_head
 * @property string $bo_include_tail
 * @property string $bo_content_head
 * @property string $bo_mobile_content_head
 * @property string $bo_content_tail
 * @property string $bo_mobile_content_tail
 * @property string $bo_insert_content
 * @property string $bo_notice
 * @property string $bo_sort_field
 * @property string $bo_1_subj
 * @property string $bo_2_subj
 * @property string $bo_3_subj
 * @property string $bo_4_subj
 * @property string $bo_5_subj
 * @property string $bo_6_subj
 * @property string $bo_7_subj
 * @property string $bo_8_subj
 * @property string $bo_9_subj
 * @property string $bo_10_subj
 * @property string $bo_1
 * @property string $bo_2
 * @property string $bo_3
 * @property string $bo_4
 * @property string $bo_5
 * @property string $bo_6
 * @property string $bo_7
 * @property string $bo_8
 * @property string $bo_9
 * @property string $bo_10
 * @property string $gr_id
 * @property string $bo_subject
 * @property string $bo_mobile_subject
 * @property string $bo_admin
 * @property string $bo_category_list
 * @property string $bo_select_editor
 * @property string $bo_skin
 * @property string $bo_mobile_skin
 * @property string $bo_include_head
 * @property string $bo_include_tail
 * @property string $bo_content_head
 * @property string $bo_mobile_content_head
 * @property string $bo_content_tail
 * @property string $bo_mobile_content_tail
 * @property string $bo_insert_content
 * @property string $bo_notice
 * @property string $bo_sort_field
 * @property string $bo_1_subj
 * @property string $bo_2_subj
 * @property string $bo_3_subj
 * @property string $bo_4_subj
 * @property string $bo_5_subj
 * @property string $bo_6_subj
 * @property string $bo_7_subj
 * @property string $bo_8_subj
 * @property string $bo_9_subj
 * @property string $bo_10_subj
 * @property string $bo_1
 * @property string $bo_2
 * @property string $bo_3
 * @property string $bo_4
 * @property string $bo_5
 * @property string $bo_6
 * @property string $bo_7
 * @property string $bo_8
 * @property string $bo_9
 * @property string $bo_10
 * @property string $gr_id
 * @property string $bo_subject
 * @property string $bo_mobile_subject
 * @property string $bo_admin
 * @property string $bo_category_list
 * @property string $bo_select_editor
 * @property string $bo_skin
 * @property string $bo_mobile_skin
 * @property string $bo_include_head
 * @property string $bo_include_tail
 * @property string $bo_content_head
 * @property string $bo_mobile_content_head
 * @property string $bo_content_tail
 * @property string $bo_mobile_content_tail
 * @property string $bo_insert_content
 * @property string $bo_notice
 * @property string $bo_sort_field
 * @property string $bo_1_subj
 * @property string $bo_2_subj
 * @property string $bo_3_subj
 * @property string $bo_4_subj
 * @property string $bo_5_subj
 * @property string $bo_6_subj
 * @property string $bo_7_subj
 * @property string $bo_8_subj
 * @property string $bo_9_subj
 * @property string $bo_10_subj
 * @property string $bo_1
 * @property string $bo_2
 * @property string $bo_3
 * @property string $bo_4
 * @property string $bo_5
 * @property string $bo_6
 * @property string $bo_7
 * @property string $bo_8
 * @property string $bo_9
 * @property string $bo_10
 * @property string $gr_id
 * @property string $bo_subject
 * @property string $bo_mobile_subject
 * @property string $bo_admin
 * @property string $bo_category_list
 * @property string $bo_select_editor
 * @property string $bo_skin
 * @property string $bo_mobile_skin
 * @property string $bo_include_head
 * @property string $bo_include_tail
 * @property string $bo_content_head
 * @property string $bo_mobile_content_head
 * @property string $bo_content_tail
 * @property string $bo_mobile_content_tail
 * @property string $bo_insert_content
 * @property string $bo_notice
 * @property string $bo_sort_field
 * @property string $bo_1_subj
 * @property string $bo_2_subj
 * @property string $bo_3_subj
 * @property string $bo_4_subj
 * @property string $bo_5_subj
 * @property string $bo_6_subj
 * @property string $bo_7_subj
 * @property string $bo_8_subj
 * @property string $bo_9_subj
 * @property string $bo_10_subj
 * @property string $bo_1
 * @property string $bo_2
 * @property string $bo_3
 * @property string $bo_4
 * @property string $bo_5
 * @property string $bo_6
 * @property string $bo_7
 * @property string $bo_8
 * @property string $bo_9
 * @property string $bo_10
 * @property string $gr_id
 * @property string $bo_subject
 * @property string $bo_mobile_subject
 * @property string $bo_admin
 * @property string $bo_category_list
 * @property string $bo_select_editor
 * @property string $bo_skin
 * @property string $bo_mobile_skin
 * @property string $bo_include_head
 * @property string $bo_include_tail
 * @property string $bo_content_head
 * @property string $bo_mobile_content_head
 * @property string $bo_content_tail
 * @property string $bo_mobile_content_tail
 * @property string $bo_insert_content
 * @property string $bo_notice
 * @property string $bo_sort_field
 * @property string $bo_1_subj
 * @property string $bo_2_subj
 * @property string $bo_3_subj
 * @property string $bo_4_subj
 * @property string $bo_5_subj
 * @property string $bo_6_subj
 * @property string $bo_7_subj
 * @property string $bo_8_subj
 * @property string $bo_9_subj
 * @property string $bo_10_subj
 * @property string $bo_1
 * @property string $bo_2
 * @property string $bo_3
 * @property string $bo_4
 * @property string $bo_5
 * @property string $bo_6
 * @property string $bo_7
 * @property string $bo_8
 * @property string $bo_9
 * @property string $bo_10
 * @property int    $bo_list_level
 * @property int    $bo_read_level
 * @property int    $bo_write_level
 * @property int    $bo_reply_level
 * @property int    $bo_comment_level
 * @property int    $bo_upload_level
 * @property int    $bo_download_level
 * @property int    $bo_html_level
 * @property int    $bo_link_level
 * @property int    $bo_count_delete
 * @property int    $bo_count_modify
 * @property int    $bo_read_point
 * @property int    $bo_write_point
 * @property int    $bo_comment_point
 * @property int    $bo_download_point
 * @property int    $bo_use_category
 * @property int    $bo_use_sideview
 * @property int    $bo_use_file_content
 * @property int    $bo_use_secret
 * @property int    $bo_use_dhtml_editor
 * @property int    $bo_use_rss_view
 * @property int    $bo_use_good
 * @property int    $bo_use_nogood
 * @property int    $bo_use_name
 * @property int    $bo_use_signature
 * @property int    $bo_use_ip_view
 * @property int    $bo_use_list_view
 * @property int    $bo_use_list_file
 * @property int    $bo_use_list_content
 * @property int    $bo_table_width
 * @property int    $bo_subject_len
 * @property int    $bo_mobile_subject_len
 * @property int    $bo_page_rows
 * @property int    $bo_mobile_page_rows
 * @property int    $bo_new
 * @property int    $bo_hot
 * @property int    $bo_image_width
 * @property int    $bo_gallery_cols
 * @property int    $bo_gallery_width
 * @property int    $bo_gallery_height
 * @property int    $bo_mobile_gallery_width
 * @property int    $bo_mobile_gallery_height
 * @property int    $bo_upload_size
 * @property int    $bo_reply_order
 * @property int    $bo_use_search
 * @property int    $bo_order
 * @property int    $bo_count_write
 * @property int    $bo_count_comment
 * @property int    $bo_write_min
 * @property int    $bo_write_max
 * @property int    $bo_comment_min
 * @property int    $bo_comment_max
 * @property int    $bo_upload_count
 * @property int    $bo_use_email
 * @property int    $bo_use_sns
 * @property int    $bo_list_level
 * @property int    $bo_read_level
 * @property int    $bo_write_level
 * @property int    $bo_reply_level
 * @property int    $bo_comment_level
 * @property int    $bo_upload_level
 * @property int    $bo_download_level
 * @property int    $bo_html_level
 * @property int    $bo_link_level
 * @property int    $bo_count_delete
 * @property int    $bo_count_modify
 * @property int    $bo_read_point
 * @property int    $bo_write_point
 * @property int    $bo_comment_point
 * @property int    $bo_download_point
 * @property int    $bo_use_category
 * @property int    $bo_use_sideview
 * @property int    $bo_use_file_content
 * @property int    $bo_use_secret
 * @property int    $bo_use_dhtml_editor
 * @property int    $bo_use_rss_view
 * @property int    $bo_use_good
 * @property int    $bo_use_nogood
 * @property int    $bo_use_name
 * @property int    $bo_use_signature
 * @property int    $bo_use_ip_view
 * @property int    $bo_use_list_view
 * @property int    $bo_use_list_file
 * @property int    $bo_use_list_content
 * @property int    $bo_table_width
 * @property int    $bo_subject_len
 * @property int    $bo_mobile_subject_len
 * @property int    $bo_page_rows
 * @property int    $bo_mobile_page_rows
 * @property int    $bo_new
 * @property int    $bo_hot
 * @property int    $bo_image_width
 * @property int    $bo_gallery_cols
 * @property int    $bo_gallery_width
 * @property int    $bo_gallery_height
 * @property int    $bo_mobile_gallery_width
 * @property int    $bo_mobile_gallery_height
 * @property int    $bo_upload_size
 * @property int    $bo_reply_order
 * @property int    $bo_use_search
 * @property int    $bo_order
 * @property int    $bo_count_write
 * @property int    $bo_count_comment
 * @property int    $bo_write_min
 * @property int    $bo_write_max
 * @property int    $bo_comment_min
 * @property int    $bo_comment_max
 * @property int    $bo_upload_count
 * @property int    $bo_use_email
 * @property int    $bo_use_sns
 * @property int    $bo_list_level
 * @property int    $bo_read_level
 * @property int    $bo_write_level
 * @property int    $bo_reply_level
 * @property int    $bo_comment_level
 * @property int    $bo_upload_level
 * @property int    $bo_download_level
 * @property int    $bo_html_level
 * @property int    $bo_link_level
 * @property int    $bo_count_delete
 * @property int    $bo_count_modify
 * @property int    $bo_read_point
 * @property int    $bo_write_point
 * @property int    $bo_comment_point
 * @property int    $bo_download_point
 * @property int    $bo_use_category
 * @property int    $bo_use_sideview
 * @property int    $bo_use_file_content
 * @property int    $bo_use_secret
 * @property int    $bo_use_dhtml_editor
 * @property int    $bo_use_rss_view
 * @property int    $bo_use_good
 * @property int    $bo_use_nogood
 * @property int    $bo_use_name
 * @property int    $bo_use_signature
 * @property int    $bo_use_ip_view
 * @property int    $bo_use_list_view
 * @property int    $bo_use_list_file
 * @property int    $bo_use_list_content
 * @property int    $bo_table_width
 * @property int    $bo_subject_len
 * @property int    $bo_mobile_subject_len
 * @property int    $bo_page_rows
 * @property int    $bo_mobile_page_rows
 * @property int    $bo_new
 * @property int    $bo_hot
 * @property int    $bo_image_width
 * @property int    $bo_gallery_cols
 * @property int    $bo_gallery_width
 * @property int    $bo_gallery_height
 * @property int    $bo_mobile_gallery_width
 * @property int    $bo_mobile_gallery_height
 * @property int    $bo_upload_size
 * @property int    $bo_reply_order
 * @property int    $bo_use_search
 * @property int    $bo_order
 * @property int    $bo_count_write
 * @property int    $bo_count_comment
 * @property int    $bo_write_min
 * @property int    $bo_write_max
 * @property int    $bo_comment_min
 * @property int    $bo_comment_max
 * @property int    $bo_upload_count
 * @property int    $bo_use_email
 * @property int    $bo_use_sns
 * @property int    $bo_use_captcha
 * @property int    $bo_list_level
 * @property int    $bo_read_level
 * @property int    $bo_write_level
 * @property int    $bo_reply_level
 * @property int    $bo_comment_level
 * @property int    $bo_upload_level
 * @property int    $bo_download_level
 * @property int    $bo_html_level
 * @property int    $bo_link_level
 * @property int    $bo_count_delete
 * @property int    $bo_count_modify
 * @property int    $bo_read_point
 * @property int    $bo_write_point
 * @property int    $bo_comment_point
 * @property int    $bo_download_point
 * @property int    $bo_use_category
 * @property int    $bo_use_sideview
 * @property int    $bo_use_file_content
 * @property int    $bo_use_secret
 * @property int    $bo_use_dhtml_editor
 * @property int    $bo_use_rss_view
 * @property int    $bo_use_good
 * @property int    $bo_use_nogood
 * @property int    $bo_use_name
 * @property int    $bo_use_signature
 * @property int    $bo_use_ip_view
 * @property int    $bo_use_list_view
 * @property int    $bo_use_list_file
 * @property int    $bo_use_list_content
 * @property int    $bo_table_width
 * @property int    $bo_subject_len
 * @property int    $bo_mobile_subject_len
 * @property int    $bo_page_rows
 * @property int    $bo_mobile_page_rows
 * @property int    $bo_new
 * @property int    $bo_hot
 * @property int    $bo_image_width
 * @property int    $bo_gallery_cols
 * @property int    $bo_gallery_width
 * @property int    $bo_gallery_height
 * @property int    $bo_mobile_gallery_width
 * @property int    $bo_mobile_gallery_height
 * @property int    $bo_upload_size
 * @property int    $bo_reply_order
 * @property int    $bo_use_search
 * @property int    $bo_order
 * @property int    $bo_count_write
 * @property int    $bo_count_comment
 * @property int    $bo_write_min
 * @property int    $bo_write_max
 * @property int    $bo_comment_min
 * @property int    $bo_comment_max
 * @property int    $bo_upload_count
 * @property int    $bo_use_email
 * @property int    $bo_use_sns
 * @property int    $bo_use_captcha
 * @property int    $bo_list_level
 * @property int    $bo_read_level
 * @property int    $bo_write_level
 * @property int    $bo_reply_level
 * @property int    $bo_comment_level
 * @property int    $bo_upload_level
 * @property int    $bo_download_level
 * @property int    $bo_html_level
 * @property int    $bo_link_level
 * @property int    $bo_count_delete
 * @property int    $bo_count_modify
 * @property int    $bo_read_point
 * @property int    $bo_write_point
 * @property int    $bo_comment_point
 * @property int    $bo_download_point
 * @property int    $bo_use_category
 * @property int    $bo_use_sideview
 * @property int    $bo_use_file_content
 * @property int    $bo_use_secret
 * @property int    $bo_use_dhtml_editor
 * @property int    $bo_use_rss_view
 * @property int    $bo_use_good
 * @property int    $bo_use_nogood
 * @property int    $bo_use_name
 * @property int    $bo_use_signature
 * @property int    $bo_use_ip_view
 * @property int    $bo_use_list_view
 * @property int    $bo_use_list_file
 * @property int    $bo_use_list_content
 * @property int    $bo_table_width
 * @property int    $bo_subject_len
 * @property int    $bo_mobile_subject_len
 * @property int    $bo_page_rows
 * @property int    $bo_mobile_page_rows
 * @property int    $bo_new
 * @property int    $bo_hot
 * @property int    $bo_image_width
 * @property int    $bo_gallery_cols
 * @property int    $bo_gallery_width
 * @property int    $bo_gallery_height
 * @property int    $bo_mobile_gallery_width
 * @property int    $bo_mobile_gallery_height
 * @property int    $bo_upload_size
 * @property int    $bo_reply_order
 * @property int    $bo_use_search
 * @property int    $bo_order
 * @property int    $bo_count_write
 * @property int    $bo_count_comment
 * @property int    $bo_write_min
 * @property int    $bo_write_max
 * @property int    $bo_comment_min
 * @property int    $bo_comment_max
 * @property int    $bo_upload_count
 * @property int    $bo_use_email
 * @property int    $bo_use_sns
 * @property int    $bo_use_captcha
 * @property int    $bo_list_level
 * @property int    $bo_read_level
 * @property int    $bo_write_level
 * @property int    $bo_reply_level
 * @property int    $bo_comment_level
 * @property int    $bo_upload_level
 * @property int    $bo_download_level
 * @property int    $bo_html_level
 * @property int    $bo_link_level
 * @property int    $bo_count_delete
 * @property int    $bo_count_modify
 * @property int    $bo_read_point
 * @property int    $bo_write_point
 * @property int    $bo_comment_point
 * @property int    $bo_download_point
 * @property int    $bo_use_category
 * @property int    $bo_use_sideview
 * @property int    $bo_use_file_content
 * @property int    $bo_use_secret
 * @property int    $bo_use_dhtml_editor
 * @property int    $bo_use_rss_view
 * @property int    $bo_use_good
 * @property int    $bo_use_nogood
 * @property int    $bo_use_name
 * @property int    $bo_use_signature
 * @property int    $bo_use_ip_view
 * @property int    $bo_use_list_view
 * @property int    $bo_use_list_file
 * @property int    $bo_use_list_content
 * @property int    $bo_table_width
 * @property int    $bo_subject_len
 * @property int    $bo_mobile_subject_len
 * @property int    $bo_page_rows
 * @property int    $bo_mobile_page_rows
 * @property int    $bo_new
 * @property int    $bo_hot
 * @property int    $bo_image_width
 * @property int    $bo_gallery_cols
 * @property int    $bo_gallery_width
 * @property int    $bo_gallery_height
 * @property int    $bo_mobile_gallery_width
 * @property int    $bo_mobile_gallery_height
 * @property int    $bo_upload_size
 * @property int    $bo_reply_order
 * @property int    $bo_use_search
 * @property int    $bo_order
 * @property int    $bo_count_write
 * @property int    $bo_count_comment
 * @property int    $bo_write_min
 * @property int    $bo_write_max
 * @property int    $bo_comment_min
 * @property int    $bo_comment_max
 * @property int    $bo_upload_count
 * @property int    $bo_use_email
 * @property int    $bo_use_sns
 * @property int    $bo_use_captcha
 * @property int    $bo_list_level
 * @property int    $bo_read_level
 * @property int    $bo_write_level
 * @property int    $bo_reply_level
 * @property int    $bo_comment_level
 * @property int    $bo_upload_level
 * @property int    $bo_download_level
 * @property int    $bo_html_level
 * @property int    $bo_link_level
 * @property int    $bo_count_delete
 * @property int    $bo_count_modify
 * @property int    $bo_read_point
 * @property int    $bo_write_point
 * @property int    $bo_comment_point
 * @property int    $bo_download_point
 * @property int    $bo_use_category
 * @property int    $bo_use_sideview
 * @property int    $bo_use_file_content
 * @property int    $bo_use_secret
 * @property int    $bo_use_dhtml_editor
 * @property int    $bo_use_rss_view
 * @property int    $bo_use_good
 * @property int    $bo_use_nogood
 * @property int    $bo_use_name
 * @property int    $bo_use_signature
 * @property int    $bo_use_ip_view
 * @property int    $bo_use_list_view
 * @property int    $bo_use_list_file
 * @property int    $bo_use_list_content
 * @property int    $bo_table_width
 * @property int    $bo_subject_len
 * @property int    $bo_mobile_subject_len
 * @property int    $bo_page_rows
 * @property int    $bo_mobile_page_rows
 * @property int    $bo_new
 * @property int    $bo_hot
 * @property int    $bo_image_width
 * @property int    $bo_gallery_cols
 * @property int    $bo_gallery_width
 * @property int    $bo_gallery_height
 * @property int    $bo_mobile_gallery_width
 * @property int    $bo_mobile_gallery_height
 * @property int    $bo_upload_size
 * @property int    $bo_reply_order
 * @property int    $bo_use_search
 * @property int    $bo_order
 * @property int    $bo_count_write
 * @property int    $bo_count_comment
 * @property int    $bo_write_min
 * @property int    $bo_write_max
 * @property int    $bo_comment_min
 * @property int    $bo_comment_max
 * @property int    $bo_upload_count
 * @property int    $bo_use_email
 * @property int    $bo_use_sns
 * @property int    $bo_use_captcha
 * @property int    $bo_list_level
 * @property int    $bo_read_level
 * @property int    $bo_write_level
 * @property int    $bo_reply_level
 * @property int    $bo_comment_level
 * @property int    $bo_upload_level
 * @property int    $bo_download_level
 * @property int    $bo_html_level
 * @property int    $bo_link_level
 * @property int    $bo_count_delete
 * @property int    $bo_count_modify
 * @property int    $bo_read_point
 * @property int    $bo_write_point
 * @property int    $bo_comment_point
 * @property int    $bo_download_point
 * @property int    $bo_use_category
 * @property int    $bo_use_sideview
 * @property int    $bo_use_file_content
 * @property int    $bo_use_secret
 * @property int    $bo_use_dhtml_editor
 * @property int    $bo_use_rss_view
 * @property int    $bo_use_good
 * @property int    $bo_use_nogood
 * @property int    $bo_use_name
 * @property int    $bo_use_signature
 * @property int    $bo_use_ip_view
 * @property int    $bo_use_list_view
 * @property int    $bo_use_list_file
 * @property int    $bo_use_list_content
 * @property int    $bo_table_width
 * @property int    $bo_subject_len
 * @property int    $bo_mobile_subject_len
 * @property int    $bo_page_rows
 * @property int    $bo_mobile_page_rows
 * @property int    $bo_new
 * @property int    $bo_hot
 * @property int    $bo_image_width
 * @property int    $bo_gallery_cols
 * @property int    $bo_gallery_width
 * @property int    $bo_gallery_height
 * @property int    $bo_mobile_gallery_width
 * @property int    $bo_mobile_gallery_height
 * @property int    $bo_upload_size
 * @property int    $bo_reply_order
 * @property int    $bo_use_search
 * @property int    $bo_order
 * @property int    $bo_count_write
 * @property int    $bo_count_comment
 * @property int    $bo_write_min
 * @property int    $bo_write_max
 * @property int    $bo_comment_min
 * @property int    $bo_comment_max
 * @property int    $bo_upload_count
 * @property int    $bo_use_email
 * @property int    $bo_use_sns
 * @property int    $bo_use_captcha
 */
class G5Board extends Model
{
    /**
     * The database table used by the model.
     *
     * @var string
     */
    protected $table = 'g5_board';

    /**
     * The primary key for the model.
     *
     * @var string
     */
    protected $primaryKey = 'bo_table';

    /**
     * Attributes that should be mass-assignable.
     *
     * @var array
     */
    protected $fillable = [
        'gr_id', 'bo_subject', 'bo_mobile_subject', 'bo_device', 'bo_admin', 'bo_list_level', 'bo_read_level', 'bo_write_level', 'bo_reply_level', 'bo_comment_level', 'bo_upload_level', 'bo_download_level', 'bo_html_level', 'bo_link_level', 'bo_count_delete', 'bo_count_modify', 'bo_read_point', 'bo_write_point', 'bo_comment_point', 'bo_download_point', 'bo_use_category', 'bo_category_list', 'bo_use_sideview', 'bo_use_file_content', 'bo_use_secret', 'bo_use_dhtml_editor', 'bo_use_rss_view', 'bo_use_good', 'bo_use_nogood', 'bo_use_name', 'bo_use_signature', 'bo_use_ip_view', 'bo_use_list_view', 'bo_use_list_file', 'bo_use_list_content', 'bo_table_width', 'bo_subject_len', 'bo_mobile_subject_len', 'bo_page_rows', 'bo_mobile_page_rows', 'bo_new', 'bo_hot', 'bo_image_width', 'bo_skin', 'bo_mobile_skin', 'bo_include_head', 'bo_include_tail', 'bo_content_head', 'bo_mobile_content_head', 'bo_content_tail', 'bo_mobile_content_tail', 'bo_insert_content', 'bo_gallery_cols', 'bo_gallery_width', 'bo_gallery_height', 'bo_mobile_gallery_width', 'bo_mobile_gallery_height', 'bo_upload_size', 'bo_reply_order', 'bo_use_search', 'bo_order', 'bo_count_write', 'bo_count_comment', 'bo_write_min', 'bo_write_max', 'bo_comment_min', 'bo_comment_max', 'bo_notice', 'bo_upload_count', 'bo_use_email', 'bo_use_cert', 'bo_use_sns', 'bo_sort_field', 'bo_1_subj', 'bo_2_subj', 'bo_3_subj', 'bo_4_subj', 'bo_5_subj', 'bo_6_subj', 'bo_7_subj', 'bo_8_subj', 'bo_9_subj', 'bo_10_subj', 'bo_1', 'bo_2', 'bo_3', 'bo_4', 'bo_5', 'bo_6', 'bo_7', 'bo_8', 'bo_9', 'bo_10', 'gr_id', 'bo_subject', 'bo_mobile_subject', 'bo_device', 'bo_admin', 'bo_list_level', 'bo_read_level', 'bo_write_level', 'bo_reply_level', 'bo_comment_level', 'bo_upload_level', 'bo_download_level', 'bo_html_level', 'bo_link_level', 'bo_count_delete', 'bo_count_modify', 'bo_read_point', 'bo_write_point', 'bo_comment_point', 'bo_download_point', 'bo_use_category', 'bo_category_list', 'bo_use_sideview', 'bo_use_file_content', 'bo_use_secret', 'bo_use_dhtml_editor', 'bo_use_rss_view', 'bo_use_good', 'bo_use_nogood', 'bo_use_name', 'bo_use_signature', 'bo_use_ip_view', 'bo_use_list_view', 'bo_use_list_file', 'bo_use_list_content', 'bo_table_width', 'bo_subject_len', 'bo_mobile_subject_len', 'bo_page_rows', 'bo_mobile_page_rows', 'bo_new', 'bo_hot', 'bo_image_width', 'bo_skin', 'bo_mobile_skin', 'bo_include_head', 'bo_include_tail', 'bo_content_head', 'bo_mobile_content_head', 'bo_content_tail', 'bo_mobile_content_tail', 'bo_insert_content', 'bo_gallery_cols', 'bo_gallery_width', 'bo_gallery_height', 'bo_mobile_gallery_width', 'bo_mobile_gallery_height', 'bo_upload_size', 'bo_reply_order', 'bo_use_search', 'bo_order', 'bo_count_write', 'bo_count_comment', 'bo_write_min', 'bo_write_max', 'bo_comment_min', 'bo_comment_max', 'bo_notice', 'bo_upload_count', 'bo_use_email', 'bo_use_cert', 'bo_use_sns', 'bo_sort_field', 'bo_1_subj', 'bo_2_subj', 'bo_3_subj', 'bo_4_subj', 'bo_5_subj', 'bo_6_subj', 'bo_7_subj', 'bo_8_subj', 'bo_9_subj', 'bo_10_subj', 'bo_1', 'bo_2', 'bo_3', 'bo_4', 'bo_5', 'bo_6', 'bo_7', 'bo_8', 'bo_9', 'bo_10', 'gr_id', 'bo_subject', 'bo_mobile_subject', 'bo_device', 'bo_admin', 'bo_list_level', 'bo_read_level', 'bo_write_level', 'bo_reply_level', 'bo_comment_level', 'bo_upload_level', 'bo_download_level', 'bo_html_level', 'bo_link_level', 'bo_count_delete', 'bo_count_modify', 'bo_read_point', 'bo_write_point', 'bo_comment_point', 'bo_download_point', 'bo_use_category', 'bo_category_list', 'bo_use_sideview', 'bo_use_file_content', 'bo_use_secret', 'bo_use_dhtml_editor', 'bo_select_editor', 'bo_use_rss_view', 'bo_use_good', 'bo_use_nogood', 'bo_use_name', 'bo_use_signature', 'bo_use_ip_view', 'bo_use_list_view', 'bo_use_list_file', 'bo_use_list_content', 'bo_table_width', 'bo_subject_len', 'bo_mobile_subject_len', 'bo_page_rows', 'bo_mobile_page_rows', 'bo_new', 'bo_hot', 'bo_image_width', 'bo_skin', 'bo_mobile_skin', 'bo_include_head', 'bo_include_tail', 'bo_content_head', 'bo_mobile_content_head', 'bo_content_tail', 'bo_mobile_content_tail', 'bo_insert_content', 'bo_gallery_cols', 'bo_gallery_width', 'bo_gallery_height', 'bo_mobile_gallery_width', 'bo_mobile_gallery_height', 'bo_upload_size', 'bo_reply_order', 'bo_use_search', 'bo_order', 'bo_count_write', 'bo_count_comment', 'bo_write_min', 'bo_write_max', 'bo_comment_min', 'bo_comment_max', 'bo_notice', 'bo_upload_count', 'bo_use_email', 'bo_use_cert', 'bo_use_sns', 'bo_use_captcha', 'bo_sort_field', 'bo_1_subj', 'bo_2_subj', 'bo_3_subj', 'bo_4_subj', 'bo_5_subj', 'bo_6_subj', 'bo_7_subj', 'bo_8_subj', 'bo_9_subj', 'bo_10_subj', 'bo_1', 'bo_2', 'bo_3', 'bo_4', 'bo_5', 'bo_6', 'bo_7', 'bo_8', 'bo_9', 'bo_10', 'gr_id', 'bo_subject', 'bo_mobile_subject', 'bo_device', 'bo_admin', 'bo_list_level', 'bo_read_level', 'bo_write_level', 'bo_reply_level', 'bo_comment_level', 'bo_upload_level', 'bo_download_level', 'bo_html_level', 'bo_link_level', 'bo_count_delete', 'bo_count_modify', 'bo_read_point', 'bo_write_point', 'bo_comment_point', 'bo_download_point', 'bo_use_category', 'bo_category_list', 'bo_use_sideview', 'bo_use_file_content', 'bo_use_secret', 'bo_use_dhtml_editor', 'bo_select_editor', 'bo_use_rss_view', 'bo_use_good', 'bo_use_nogood', 'bo_use_name', 'bo_use_signature', 'bo_use_ip_view', 'bo_use_list_view', 'bo_use_list_file', 'bo_use_list_content', 'bo_table_width', 'bo_subject_len', 'bo_mobile_subject_len', 'bo_page_rows', 'bo_mobile_page_rows', 'bo_new', 'bo_hot', 'bo_image_width', 'bo_skin', 'bo_mobile_skin', 'bo_include_head', 'bo_include_tail', 'bo_content_head', 'bo_mobile_content_head', 'bo_content_tail', 'bo_mobile_content_tail', 'bo_insert_content', 'bo_gallery_cols', 'bo_gallery_width', 'bo_gallery_height', 'bo_mobile_gallery_width', 'bo_mobile_gallery_height', 'bo_upload_size', 'bo_reply_order', 'bo_use_search', 'bo_order', 'bo_count_write', 'bo_count_comment', 'bo_write_min', 'bo_write_max', 'bo_comment_min', 'bo_comment_max', 'bo_notice', 'bo_upload_count', 'bo_use_email', 'bo_use_cert', 'bo_use_sns', 'bo_use_captcha', 'bo_sort_field', 'bo_1_subj', 'bo_2_subj', 'bo_3_subj', 'bo_4_subj', 'bo_5_subj', 'bo_6_subj', 'bo_7_subj', 'bo_8_subj', 'bo_9_subj', 'bo_10_subj', 'bo_1', 'bo_2', 'bo_3', 'bo_4', 'bo_5', 'bo_6', 'bo_7', 'bo_8', 'bo_9', 'bo_10', 'gr_id', 'bo_subject', 'bo_mobile_subject', 'bo_device', 'bo_admin', 'bo_list_level', 'bo_read_level', 'bo_write_level', 'bo_reply_level', 'bo_comment_level', 'bo_upload_level', 'bo_download_level', 'bo_html_level', 'bo_link_level', 'bo_count_delete', 'bo_count_modify', 'bo_read_point', 'bo_write_point', 'bo_comment_point', 'bo_download_point', 'bo_use_category', 'bo_category_list', 'bo_use_sideview', 'bo_use_file_content', 'bo_use_secret', 'bo_use_dhtml_editor', 'bo_select_editor', 'bo_use_rss_view', 'bo_use_good', 'bo_use_nogood', 'bo_use_name', 'bo_use_signature', 'bo_use_ip_view', 'bo_use_list_view', 'bo_use_list_file', 'bo_use_list_content', 'bo_table_width', 'bo_subject_len', 'bo_mobile_subject_len', 'bo_page_rows', 'bo_mobile_page_rows', 'bo_new', 'bo_hot', 'bo_image_width', 'bo_skin', 'bo_mobile_skin', 'bo_include_head', 'bo_include_tail', 'bo_content_head', 'bo_mobile_content_head', 'bo_content_tail', 'bo_mobile_content_tail', 'bo_insert_content', 'bo_gallery_cols', 'bo_gallery_width', 'bo_gallery_height', 'bo_mobile_gallery_width', 'bo_mobile_gallery_height', 'bo_upload_size', 'bo_reply_order', 'bo_use_search', 'bo_order', 'bo_count_write', 'bo_count_comment', 'bo_write_min', 'bo_write_max', 'bo_comment_min', 'bo_comment_max', 'bo_notice', 'bo_upload_count', 'bo_use_email', 'bo_use_cert', 'bo_use_sns', 'bo_use_captcha', 'bo_sort_field', 'bo_1_subj', 'bo_2_subj', 'bo_3_subj', 'bo_4_subj', 'bo_5_subj', 'bo_6_subj', 'bo_7_subj', 'bo_8_subj', 'bo_9_subj', 'bo_10_subj', 'bo_1', 'bo_2', 'bo_3', 'bo_4', 'bo_5', 'bo_6', 'bo_7', 'bo_8', 'bo_9', 'bo_10', 'gr_id', 'bo_subject', 'bo_mobile_subject', 'bo_device', 'bo_admin', 'bo_list_level', 'bo_read_level', 'bo_write_level', 'bo_reply_level', 'bo_comment_level', 'bo_upload_level', 'bo_download_level', 'bo_html_level', 'bo_link_level', 'bo_count_delete', 'bo_count_modify', 'bo_read_point', 'bo_write_point', 'bo_comment_point', 'bo_download_point', 'bo_use_category', 'bo_category_list', 'bo_use_sideview', 'bo_use_file_content', 'bo_use_secret', 'bo_use_dhtml_editor', 'bo_select_editor', 'bo_use_rss_view', 'bo_use_good', 'bo_use_nogood', 'bo_use_name', 'bo_use_signature', 'bo_use_ip_view', 'bo_use_list_view', 'bo_use_list_file', 'bo_use_list_content', 'bo_table_width', 'bo_subject_len', 'bo_mobile_subject_len', 'bo_page_rows', 'bo_mobile_page_rows', 'bo_new', 'bo_hot', 'bo_image_width', 'bo_skin', 'bo_mobile_skin', 'bo_include_head', 'bo_include_tail', 'bo_content_head', 'bo_mobile_content_head', 'bo_content_tail', 'bo_mobile_content_tail', 'bo_insert_content', 'bo_gallery_cols', 'bo_gallery_width', 'bo_gallery_height', 'bo_mobile_gallery_width', 'bo_mobile_gallery_height', 'bo_upload_size', 'bo_reply_order', 'bo_use_search', 'bo_order', 'bo_count_write', 'bo_count_comment', 'bo_write_min', 'bo_write_max', 'bo_comment_min', 'bo_comment_max', 'bo_notice', 'bo_upload_count', 'bo_use_email', 'bo_use_cert', 'bo_use_sns', 'bo_use_captcha', 'bo_sort_field', 'bo_1_subj', 'bo_2_subj', 'bo_3_subj', 'bo_4_subj', 'bo_5_subj', 'bo_6_subj', 'bo_7_subj', 'bo_8_subj', 'bo_9_subj', 'bo_10_subj', 'bo_1', 'bo_2', 'bo_3', 'bo_4', 'bo_5', 'bo_6', 'bo_7', 'bo_8', 'bo_9', 'bo_10', 'gr_id', 'bo_subject', 'bo_mobile_subject', 'bo_device', 'bo_admin', 'bo_list_level', 'bo_read_level', 'bo_write_level', 'bo_reply_level', 'bo_comment_level', 'bo_upload_level', 'bo_download_level', 'bo_html_level', 'bo_link_level', 'bo_count_delete', 'bo_count_modify', 'bo_read_point', 'bo_write_point', 'bo_comment_point', 'bo_download_point', 'bo_use_category', 'bo_category_list', 'bo_use_sideview', 'bo_use_file_content', 'bo_use_secret', 'bo_use_dhtml_editor', 'bo_select_editor', 'bo_use_rss_view', 'bo_use_good', 'bo_use_nogood', 'bo_use_name', 'bo_use_signature', 'bo_use_ip_view', 'bo_use_list_view', 'bo_use_list_file', 'bo_use_list_content', 'bo_table_width', 'bo_subject_len', 'bo_mobile_subject_len', 'bo_page_rows', 'bo_mobile_page_rows', 'bo_new', 'bo_hot', 'bo_image_width', 'bo_skin', 'bo_mobile_skin', 'bo_include_head', 'bo_include_tail', 'bo_content_head', 'bo_mobile_content_head', 'bo_content_tail', 'bo_mobile_content_tail', 'bo_insert_content', 'bo_gallery_cols', 'bo_gallery_width', 'bo_gallery_height', 'bo_mobile_gallery_width', 'bo_mobile_gallery_height', 'bo_upload_size', 'bo_reply_order', 'bo_use_search', 'bo_order', 'bo_count_write', 'bo_count_comment', 'bo_write_min', 'bo_write_max', 'bo_comment_min', 'bo_comment_max', 'bo_notice', 'bo_upload_count', 'bo_use_email', 'bo_use_cert', 'bo_use_sns', 'bo_use_captcha', 'bo_sort_field', 'bo_1_subj', 'bo_2_subj', 'bo_3_subj', 'bo_4_subj', 'bo_5_subj', 'bo_6_subj', 'bo_7_subj', 'bo_8_subj', 'bo_9_subj', 'bo_10_subj', 'bo_1', 'bo_2', 'bo_3', 'bo_4', 'bo_5', 'bo_6', 'bo_7', 'bo_8', 'bo_9', 'bo_10', 'gr_id', 'bo_subject', 'bo_mobile_subject', 'bo_device', 'bo_admin', 'bo_list_level', 'bo_read_level', 'bo_write_level', 'bo_reply_level', 'bo_comment_level', 'bo_upload_level', 'bo_download_level', 'bo_html_level', 'bo_link_level', 'bo_count_delete', 'bo_count_modify', 'bo_read_point', 'bo_write_point', 'bo_comment_point', 'bo_download_point', 'bo_use_category', 'bo_category_list', 'bo_use_sideview', 'bo_use_file_content', 'bo_use_secret', 'bo_use_dhtml_editor', 'bo_select_editor', 'bo_use_rss_view', 'bo_use_good', 'bo_use_nogood', 'bo_use_name', 'bo_use_signature', 'bo_use_ip_view', 'bo_use_list_view', 'bo_use_list_file', 'bo_use_list_content', 'bo_table_width', 'bo_subject_len', 'bo_mobile_subject_len', 'bo_page_rows', 'bo_mobile_page_rows', 'bo_new', 'bo_hot', 'bo_image_width', 'bo_skin', 'bo_mobile_skin', 'bo_include_head', 'bo_include_tail', 'bo_content_head', 'bo_mobile_content_head', 'bo_content_tail', 'bo_mobile_content_tail', 'bo_insert_content', 'bo_gallery_cols', 'bo_gallery_width', 'bo_gallery_height', 'bo_mobile_gallery_width', 'bo_mobile_gallery_height', 'bo_upload_size', 'bo_reply_order', 'bo_use_search', 'bo_order', 'bo_count_write', 'bo_count_comment', 'bo_write_min', 'bo_write_max', 'bo_comment_min', 'bo_comment_max', 'bo_notice', 'bo_upload_count', 'bo_use_email', 'bo_use_cert', 'bo_use_sns', 'bo_use_captcha', 'bo_sort_field', 'bo_1_subj', 'bo_2_subj', 'bo_3_subj', 'bo_4_subj', 'bo_5_subj', 'bo_6_subj', 'bo_7_subj', 'bo_8_subj', 'bo_9_subj', 'bo_10_subj', 'bo_1', 'bo_2', 'bo_3', 'bo_4', 'bo_5', 'bo_6', 'bo_7', 'bo_8', 'bo_9', 'bo_10'
    ];

    /**
     * The attributes excluded from the model's JSON form.
     *
     * @var array
     */
    protected $hidden = [
        
    ];

    /**
     * The attributes that should be casted to native types.
     *
     * @var array
     */
    protected $casts = [
        'bo_table' => 'string', 'bo_table' => 'string', 'bo_table' => 'string', 'bo_table' => 'string', 'bo_table' => 'string', 'bo_table' => 'string', 'bo_table' => 'string', 'bo_table' => 'string', 'gr_id' => 'string', 'bo_subject' => 'string', 'bo_mobile_subject' => 'string', 'bo_admin' => 'string', 'bo_list_level' => 'int', 'bo_read_level' => 'int', 'bo_write_level' => 'int', 'bo_reply_level' => 'int', 'bo_comment_level' => 'int', 'bo_upload_level' => 'int', 'bo_download_level' => 'int', 'bo_html_level' => 'int', 'bo_link_level' => 'int', 'bo_count_delete' => 'int', 'bo_count_modify' => 'int', 'bo_read_point' => 'int', 'bo_write_point' => 'int', 'bo_comment_point' => 'int', 'bo_download_point' => 'int', 'bo_use_category' => 'int', 'bo_category_list' => 'string', 'bo_use_sideview' => 'int', 'bo_use_file_content' => 'int', 'bo_use_secret' => 'int', 'bo_use_dhtml_editor' => 'int', 'bo_use_rss_view' => 'int', 'bo_use_good' => 'int', 'bo_use_nogood' => 'int', 'bo_use_name' => 'int', 'bo_use_signature' => 'int', 'bo_use_ip_view' => 'int', 'bo_use_list_view' => 'int', 'bo_use_list_file' => 'int', 'bo_use_list_content' => 'int', 'bo_table_width' => 'int', 'bo_subject_len' => 'int', 'bo_mobile_subject_len' => 'int', 'bo_page_rows' => 'int', 'bo_mobile_page_rows' => 'int', 'bo_new' => 'int', 'bo_hot' => 'int', 'bo_image_width' => 'int', 'bo_skin' => 'string', 'bo_mobile_skin' => 'string', 'bo_include_head' => 'string', 'bo_include_tail' => 'string', 'bo_content_head' => 'string', 'bo_mobile_content_head' => 'string', 'bo_content_tail' => 'string', 'bo_mobile_content_tail' => 'string', 'bo_insert_content' => 'string', 'bo_gallery_cols' => 'int', 'bo_gallery_width' => 'int', 'bo_gallery_height' => 'int', 'bo_mobile_gallery_width' => 'int', 'bo_mobile_gallery_height' => 'int', 'bo_upload_size' => 'int', 'bo_reply_order' => 'int', 'bo_use_search' => 'int', 'bo_order' => 'int', 'bo_count_write' => 'int', 'bo_count_comment' => 'int', 'bo_write_min' => 'int', 'bo_write_max' => 'int', 'bo_comment_min' => 'int', 'bo_comment_max' => 'int', 'bo_notice' => 'string', 'bo_upload_count' => 'int', 'bo_use_email' => 'int', 'bo_use_sns' => 'int', 'bo_sort_field' => 'string', 'bo_1_subj' => 'string', 'bo_2_subj' => 'string', 'bo_3_subj' => 'string', 'bo_4_subj' => 'string', 'bo_5_subj' => 'string', 'bo_6_subj' => 'string', 'bo_7_subj' => 'string', 'bo_8_subj' => 'string', 'bo_9_subj' => 'string', 'bo_10_subj' => 'string', 'bo_1' => 'string', 'bo_2' => 'string', 'bo_3' => 'string', 'bo_4' => 'string', 'bo_5' => 'string', 'bo_6' => 'string', 'bo_7' => 'string', 'bo_8' => 'string', 'bo_9' => 'string', 'bo_10' => 'string', 'gr_id' => 'string', 'bo_subject' => 'string', 'bo_mobile_subject' => 'string', 'bo_admin' => 'string', 'bo_list_level' => 'int', 'bo_read_level' => 'int', 'bo_write_level' => 'int', 'bo_reply_level' => 'int', 'bo_comment_level' => 'int', 'bo_upload_level' => 'int', 'bo_download_level' => 'int', 'bo_html_level' => 'int', 'bo_link_level' => 'int', 'bo_count_delete' => 'int', 'bo_count_modify' => 'int', 'bo_read_point' => 'int', 'bo_write_point' => 'int', 'bo_comment_point' => 'int', 'bo_download_point' => 'int', 'bo_use_category' => 'int', 'bo_category_list' => 'string', 'bo_use_sideview' => 'int', 'bo_use_file_content' => 'int', 'bo_use_secret' => 'int', 'bo_use_dhtml_editor' => 'int', 'bo_use_rss_view' => 'int', 'bo_use_good' => 'int', 'bo_use_nogood' => 'int', 'bo_use_name' => 'int', 'bo_use_signature' => 'int', 'bo_use_ip_view' => 'int', 'bo_use_list_view' => 'int', 'bo_use_list_file' => 'int', 'bo_use_list_content' => 'int', 'bo_table_width' => 'int', 'bo_subject_len' => 'int', 'bo_mobile_subject_len' => 'int', 'bo_page_rows' => 'int', 'bo_mobile_page_rows' => 'int', 'bo_new' => 'int', 'bo_hot' => 'int', 'bo_image_width' => 'int', 'bo_skin' => 'string', 'bo_mobile_skin' => 'string', 'bo_include_head' => 'string', 'bo_include_tail' => 'string', 'bo_content_head' => 'string', 'bo_mobile_content_head' => 'string', 'bo_content_tail' => 'string', 'bo_mobile_content_tail' => 'string', 'bo_insert_content' => 'string', 'bo_gallery_cols' => 'int', 'bo_gallery_width' => 'int', 'bo_gallery_height' => 'int', 'bo_mobile_gallery_width' => 'int', 'bo_mobile_gallery_height' => 'int', 'bo_upload_size' => 'int', 'bo_reply_order' => 'int', 'bo_use_search' => 'int', 'bo_order' => 'int', 'bo_count_write' => 'int', 'bo_count_comment' => 'int', 'bo_write_min' => 'int', 'bo_write_max' => 'int', 'bo_comment_min' => 'int', 'bo_comment_max' => 'int', 'bo_notice' => 'string', 'bo_upload_count' => 'int', 'bo_use_email' => 'int', 'bo_use_sns' => 'int', 'bo_sort_field' => 'string', 'bo_1_subj' => 'string', 'bo_2_subj' => 'string', 'bo_3_subj' => 'string', 'bo_4_subj' => 'string', 'bo_5_subj' => 'string', 'bo_6_subj' => 'string', 'bo_7_subj' => 'string', 'bo_8_subj' => 'string', 'bo_9_subj' => 'string', 'bo_10_subj' => 'string', 'bo_1' => 'string', 'bo_2' => 'string', 'bo_3' => 'string', 'bo_4' => 'string', 'bo_5' => 'string', 'bo_6' => 'string', 'bo_7' => 'string', 'bo_8' => 'string', 'bo_9' => 'string', 'bo_10' => 'string', 'gr_id' => 'string', 'bo_subject' => 'string', 'bo_mobile_subject' => 'string', 'bo_admin' => 'string', 'bo_list_level' => 'int', 'bo_read_level' => 'int', 'bo_write_level' => 'int', 'bo_reply_level' => 'int', 'bo_comment_level' => 'int', 'bo_upload_level' => 'int', 'bo_download_level' => 'int', 'bo_html_level' => 'int', 'bo_link_level' => 'int', 'bo_count_delete' => 'int', 'bo_count_modify' => 'int', 'bo_read_point' => 'int', 'bo_write_point' => 'int', 'bo_comment_point' => 'int', 'bo_download_point' => 'int', 'bo_use_category' => 'int', 'bo_category_list' => 'string', 'bo_use_sideview' => 'int', 'bo_use_file_content' => 'int', 'bo_use_secret' => 'int', 'bo_use_dhtml_editor' => 'int', 'bo_select_editor' => 'string', 'bo_use_rss_view' => 'int', 'bo_use_good' => 'int', 'bo_use_nogood' => 'int', 'bo_use_name' => 'int', 'bo_use_signature' => 'int', 'bo_use_ip_view' => 'int', 'bo_use_list_view' => 'int', 'bo_use_list_file' => 'int', 'bo_use_list_content' => 'int', 'bo_table_width' => 'int', 'bo_subject_len' => 'int', 'bo_mobile_subject_len' => 'int', 'bo_page_rows' => 'int', 'bo_mobile_page_rows' => 'int', 'bo_new' => 'int', 'bo_hot' => 'int', 'bo_image_width' => 'int', 'bo_skin' => 'string', 'bo_mobile_skin' => 'string', 'bo_include_head' => 'string', 'bo_include_tail' => 'string', 'bo_content_head' => 'string', 'bo_mobile_content_head' => 'string', 'bo_content_tail' => 'string', 'bo_mobile_content_tail' => 'string', 'bo_insert_content' => 'string', 'bo_gallery_cols' => 'int', 'bo_gallery_width' => 'int', 'bo_gallery_height' => 'int', 'bo_mobile_gallery_width' => 'int', 'bo_mobile_gallery_height' => 'int', 'bo_upload_size' => 'int', 'bo_reply_order' => 'int', 'bo_use_search' => 'int', 'bo_order' => 'int', 'bo_count_write' => 'int', 'bo_count_comment' => 'int', 'bo_write_min' => 'int', 'bo_write_max' => 'int', 'bo_comment_min' => 'int', 'bo_comment_max' => 'int', 'bo_notice' => 'string', 'bo_upload_count' => 'int', 'bo_use_email' => 'int', 'bo_use_sns' => 'int', 'bo_use_captcha' => 'int', 'bo_sort_field' => 'string', 'bo_1_subj' => 'string', 'bo_2_subj' => 'string', 'bo_3_subj' => 'string', 'bo_4_subj' => 'string', 'bo_5_subj' => 'string', 'bo_6_subj' => 'string', 'bo_7_subj' => 'string', 'bo_8_subj' => 'string', 'bo_9_subj' => 'string', 'bo_10_subj' => 'string', 'bo_1' => 'string', 'bo_2' => 'string', 'bo_3' => 'string', 'bo_4' => 'string', 'bo_5' => 'string', 'bo_6' => 'string', 'bo_7' => 'string', 'bo_8' => 'string', 'bo_9' => 'string', 'bo_10' => 'string', 'gr_id' => 'string', 'bo_subject' => 'string', 'bo_mobile_subject' => 'string', 'bo_admin' => 'string', 'bo_list_level' => 'int', 'bo_read_level' => 'int', 'bo_write_level' => 'int', 'bo_reply_level' => 'int', 'bo_comment_level' => 'int', 'bo_upload_level' => 'int', 'bo_download_level' => 'int', 'bo_html_level' => 'int', 'bo_link_level' => 'int', 'bo_count_delete' => 'int', 'bo_count_modify' => 'int', 'bo_read_point' => 'int', 'bo_write_point' => 'int', 'bo_comment_point' => 'int', 'bo_download_point' => 'int', 'bo_use_category' => 'int', 'bo_category_list' => 'string', 'bo_use_sideview' => 'int', 'bo_use_file_content' => 'int', 'bo_use_secret' => 'int', 'bo_use_dhtml_editor' => 'int', 'bo_select_editor' => 'string', 'bo_use_rss_view' => 'int', 'bo_use_good' => 'int', 'bo_use_nogood' => 'int', 'bo_use_name' => 'int', 'bo_use_signature' => 'int', 'bo_use_ip_view' => 'int', 'bo_use_list_view' => 'int', 'bo_use_list_file' => 'int', 'bo_use_list_content' => 'int', 'bo_table_width' => 'int', 'bo_subject_len' => 'int', 'bo_mobile_subject_len' => 'int', 'bo_page_rows' => 'int', 'bo_mobile_page_rows' => 'int', 'bo_new' => 'int', 'bo_hot' => 'int', 'bo_image_width' => 'int', 'bo_skin' => 'string', 'bo_mobile_skin' => 'string', 'bo_include_head' => 'string', 'bo_include_tail' => 'string', 'bo_content_head' => 'string', 'bo_mobile_content_head' => 'string', 'bo_content_tail' => 'string', 'bo_mobile_content_tail' => 'string', 'bo_insert_content' => 'string', 'bo_gallery_cols' => 'int', 'bo_gallery_width' => 'int', 'bo_gallery_height' => 'int', 'bo_mobile_gallery_width' => 'int', 'bo_mobile_gallery_height' => 'int', 'bo_upload_size' => 'int', 'bo_reply_order' => 'int', 'bo_use_search' => 'int', 'bo_order' => 'int', 'bo_count_write' => 'int', 'bo_count_comment' => 'int', 'bo_write_min' => 'int', 'bo_write_max' => 'int', 'bo_comment_min' => 'int', 'bo_comment_max' => 'int', 'bo_notice' => 'string', 'bo_upload_count' => 'int', 'bo_use_email' => 'int', 'bo_use_sns' => 'int', 'bo_use_captcha' => 'int', 'bo_sort_field' => 'string', 'bo_1_subj' => 'string', 'bo_2_subj' => 'string', 'bo_3_subj' => 'string', 'bo_4_subj' => 'string', 'bo_5_subj' => 'string', 'bo_6_subj' => 'string', 'bo_7_subj' => 'string', 'bo_8_subj' => 'string', 'bo_9_subj' => 'string', 'bo_10_subj' => 'string', 'bo_1' => 'string', 'bo_2' => 'string', 'bo_3' => 'string', 'bo_4' => 'string', 'bo_5' => 'string', 'bo_6' => 'string', 'bo_7' => 'string', 'bo_8' => 'string', 'bo_9' => 'string', 'bo_10' => 'string', 'gr_id' => 'string', 'bo_subject' => 'string', 'bo_mobile_subject' => 'string', 'bo_admin' => 'string', 'bo_list_level' => 'int', 'bo_read_level' => 'int', 'bo_write_level' => 'int', 'bo_reply_level' => 'int', 'bo_comment_level' => 'int', 'bo_upload_level' => 'int', 'bo_download_level' => 'int', 'bo_html_level' => 'int', 'bo_link_level' => 'int', 'bo_count_delete' => 'int', 'bo_count_modify' => 'int', 'bo_read_point' => 'int', 'bo_write_point' => 'int', 'bo_comment_point' => 'int', 'bo_download_point' => 'int', 'bo_use_category' => 'int', 'bo_category_list' => 'string', 'bo_use_sideview' => 'int', 'bo_use_file_content' => 'int', 'bo_use_secret' => 'int', 'bo_use_dhtml_editor' => 'int', 'bo_select_editor' => 'string', 'bo_use_rss_view' => 'int', 'bo_use_good' => 'int', 'bo_use_nogood' => 'int', 'bo_use_name' => 'int', 'bo_use_signature' => 'int', 'bo_use_ip_view' => 'int', 'bo_use_list_view' => 'int', 'bo_use_list_file' => 'int', 'bo_use_list_content' => 'int', 'bo_table_width' => 'int', 'bo_subject_len' => 'int', 'bo_mobile_subject_len' => 'int', 'bo_page_rows' => 'int', 'bo_mobile_page_rows' => 'int', 'bo_new' => 'int', 'bo_hot' => 'int', 'bo_image_width' => 'int', 'bo_skin' => 'string', 'bo_mobile_skin' => 'string', 'bo_include_head' => 'string', 'bo_include_tail' => 'string', 'bo_content_head' => 'string', 'bo_mobile_content_head' => 'string', 'bo_content_tail' => 'string', 'bo_mobile_content_tail' => 'string', 'bo_insert_content' => 'string', 'bo_gallery_cols' => 'int', 'bo_gallery_width' => 'int', 'bo_gallery_height' => 'int', 'bo_mobile_gallery_width' => 'int', 'bo_mobile_gallery_height' => 'int', 'bo_upload_size' => 'int', 'bo_reply_order' => 'int', 'bo_use_search' => 'int', 'bo_order' => 'int', 'bo_count_write' => 'int', 'bo_count_comment' => 'int', 'bo_write_min' => 'int', 'bo_write_max' => 'int', 'bo_comment_min' => 'int', 'bo_comment_max' => 'int', 'bo_notice' => 'string', 'bo_upload_count' => 'int', 'bo_use_email' => 'int', 'bo_use_sns' => 'int', 'bo_use_captcha' => 'int', 'bo_sort_field' => 'string', 'bo_1_subj' => 'string', 'bo_2_subj' => 'string', 'bo_3_subj' => 'string', 'bo_4_subj' => 'string', 'bo_5_subj' => 'string', 'bo_6_subj' => 'string', 'bo_7_subj' => 'string', 'bo_8_subj' => 'string', 'bo_9_subj' => 'string', 'bo_10_subj' => 'string', 'bo_1' => 'string', 'bo_2' => 'string', 'bo_3' => 'string', 'bo_4' => 'string', 'bo_5' => 'string', 'bo_6' => 'string', 'bo_7' => 'string', 'bo_8' => 'string', 'bo_9' => 'string', 'bo_10' => 'string', 'gr_id' => 'string', 'bo_subject' => 'string', 'bo_mobile_subject' => 'string', 'bo_admin' => 'string', 'bo_list_level' => 'int', 'bo_read_level' => 'int', 'bo_write_level' => 'int', 'bo_reply_level' => 'int', 'bo_comment_level' => 'int', 'bo_upload_level' => 'int', 'bo_download_level' => 'int', 'bo_html_level' => 'int', 'bo_link_level' => 'int', 'bo_count_delete' => 'int', 'bo_count_modify' => 'int', 'bo_read_point' => 'int', 'bo_write_point' => 'int', 'bo_comment_point' => 'int', 'bo_download_point' => 'int', 'bo_use_category' => 'int', 'bo_category_list' => 'string', 'bo_use_sideview' => 'int', 'bo_use_file_content' => 'int', 'bo_use_secret' => 'int', 'bo_use_dhtml_editor' => 'int', 'bo_select_editor' => 'string', 'bo_use_rss_view' => 'int', 'bo_use_good' => 'int', 'bo_use_nogood' => 'int', 'bo_use_name' => 'int', 'bo_use_signature' => 'int', 'bo_use_ip_view' => 'int', 'bo_use_list_view' => 'int', 'bo_use_list_file' => 'int', 'bo_use_list_content' => 'int', 'bo_table_width' => 'int', 'bo_subject_len' => 'int', 'bo_mobile_subject_len' => 'int', 'bo_page_rows' => 'int', 'bo_mobile_page_rows' => 'int', 'bo_new' => 'int', 'bo_hot' => 'int', 'bo_image_width' => 'int', 'bo_skin' => 'string', 'bo_mobile_skin' => 'string', 'bo_include_head' => 'string', 'bo_include_tail' => 'string', 'bo_content_head' => 'string', 'bo_mobile_content_head' => 'string', 'bo_content_tail' => 'string', 'bo_mobile_content_tail' => 'string', 'bo_insert_content' => 'string', 'bo_gallery_cols' => 'int', 'bo_gallery_width' => 'int', 'bo_gallery_height' => 'int', 'bo_mobile_gallery_width' => 'int', 'bo_mobile_gallery_height' => 'int', 'bo_upload_size' => 'int', 'bo_reply_order' => 'int', 'bo_use_search' => 'int', 'bo_order' => 'int', 'bo_count_write' => 'int', 'bo_count_comment' => 'int', 'bo_write_min' => 'int', 'bo_write_max' => 'int', 'bo_comment_min' => 'int', 'bo_comment_max' => 'int', 'bo_notice' => 'string', 'bo_upload_count' => 'int', 'bo_use_email' => 'int', 'bo_use_sns' => 'int', 'bo_use_captcha' => 'int', 'bo_sort_field' => 'string', 'bo_1_subj' => 'string', 'bo_2_subj' => 'string', 'bo_3_subj' => 'string', 'bo_4_subj' => 'string', 'bo_5_subj' => 'string', 'bo_6_subj' => 'string', 'bo_7_subj' => 'string', 'bo_8_subj' => 'string', 'bo_9_subj' => 'string', 'bo_10_subj' => 'string', 'bo_1' => 'string', 'bo_2' => 'string', 'bo_3' => 'string', 'bo_4' => 'string', 'bo_5' => 'string', 'bo_6' => 'string', 'bo_7' => 'string', 'bo_8' => 'string', 'bo_9' => 'string', 'bo_10' => 'string', 'gr_id' => 'string', 'bo_subject' => 'string', 'bo_mobile_subject' => 'string', 'bo_admin' => 'string', 'bo_list_level' => 'int', 'bo_read_level' => 'int', 'bo_write_level' => 'int', 'bo_reply_level' => 'int', 'bo_comment_level' => 'int', 'bo_upload_level' => 'int', 'bo_download_level' => 'int', 'bo_html_level' => 'int', 'bo_link_level' => 'int', 'bo_count_delete' => 'int', 'bo_count_modify' => 'int', 'bo_read_point' => 'int', 'bo_write_point' => 'int', 'bo_comment_point' => 'int', 'bo_download_point' => 'int', 'bo_use_category' => 'int', 'bo_category_list' => 'string', 'bo_use_sideview' => 'int', 'bo_use_file_content' => 'int', 'bo_use_secret' => 'int', 'bo_use_dhtml_editor' => 'int', 'bo_select_editor' => 'string', 'bo_use_rss_view' => 'int', 'bo_use_good' => 'int', 'bo_use_nogood' => 'int', 'bo_use_name' => 'int', 'bo_use_signature' => 'int', 'bo_use_ip_view' => 'int', 'bo_use_list_view' => 'int', 'bo_use_list_file' => 'int', 'bo_use_list_content' => 'int', 'bo_table_width' => 'int', 'bo_subject_len' => 'int', 'bo_mobile_subject_len' => 'int', 'bo_page_rows' => 'int', 'bo_mobile_page_rows' => 'int', 'bo_new' => 'int', 'bo_hot' => 'int', 'bo_image_width' => 'int', 'bo_skin' => 'string', 'bo_mobile_skin' => 'string', 'bo_include_head' => 'string', 'bo_include_tail' => 'string', 'bo_content_head' => 'string', 'bo_mobile_content_head' => 'string', 'bo_content_tail' => 'string', 'bo_mobile_content_tail' => 'string', 'bo_insert_content' => 'string', 'bo_gallery_cols' => 'int', 'bo_gallery_width' => 'int', 'bo_gallery_height' => 'int', 'bo_mobile_gallery_width' => 'int', 'bo_mobile_gallery_height' => 'int', 'bo_upload_size' => 'int', 'bo_reply_order' => 'int', 'bo_use_search' => 'int', 'bo_order' => 'int', 'bo_count_write' => 'int', 'bo_count_comment' => 'int', 'bo_write_min' => 'int', 'bo_write_max' => 'int', 'bo_comment_min' => 'int', 'bo_comment_max' => 'int', 'bo_notice' => 'string', 'bo_upload_count' => 'int', 'bo_use_email' => 'int', 'bo_use_sns' => 'int', 'bo_use_captcha' => 'int', 'bo_sort_field' => 'string', 'bo_1_subj' => 'string', 'bo_2_subj' => 'string', 'bo_3_subj' => 'string', 'bo_4_subj' => 'string', 'bo_5_subj' => 'string', 'bo_6_subj' => 'string', 'bo_7_subj' => 'string', 'bo_8_subj' => 'string', 'bo_9_subj' => 'string', 'bo_10_subj' => 'string', 'bo_1' => 'string', 'bo_2' => 'string', 'bo_3' => 'string', 'bo_4' => 'string', 'bo_5' => 'string', 'bo_6' => 'string', 'bo_7' => 'string', 'bo_8' => 'string', 'bo_9' => 'string', 'bo_10' => 'string', 'gr_id' => 'string', 'bo_subject' => 'string', 'bo_mobile_subject' => 'string', 'bo_admin' => 'string', 'bo_list_level' => 'int', 'bo_read_level' => 'int', 'bo_write_level' => 'int', 'bo_reply_level' => 'int', 'bo_comment_level' => 'int', 'bo_upload_level' => 'int', 'bo_download_level' => 'int', 'bo_html_level' => 'int', 'bo_link_level' => 'int', 'bo_count_delete' => 'int', 'bo_count_modify' => 'int', 'bo_read_point' => 'int', 'bo_write_point' => 'int', 'bo_comment_point' => 'int', 'bo_download_point' => 'int', 'bo_use_category' => 'int', 'bo_category_list' => 'string', 'bo_use_sideview' => 'int', 'bo_use_file_content' => 'int', 'bo_use_secret' => 'int', 'bo_use_dhtml_editor' => 'int', 'bo_select_editor' => 'string', 'bo_use_rss_view' => 'int', 'bo_use_good' => 'int', 'bo_use_nogood' => 'int', 'bo_use_name' => 'int', 'bo_use_signature' => 'int', 'bo_use_ip_view' => 'int', 'bo_use_list_view' => 'int', 'bo_use_list_file' => 'int', 'bo_use_list_content' => 'int', 'bo_table_width' => 'int', 'bo_subject_len' => 'int', 'bo_mobile_subject_len' => 'int', 'bo_page_rows' => 'int', 'bo_mobile_page_rows' => 'int', 'bo_new' => 'int', 'bo_hot' => 'int', 'bo_image_width' => 'int', 'bo_skin' => 'string', 'bo_mobile_skin' => 'string', 'bo_include_head' => 'string', 'bo_include_tail' => 'string', 'bo_content_head' => 'string', 'bo_mobile_content_head' => 'string', 'bo_content_tail' => 'string', 'bo_mobile_content_tail' => 'string', 'bo_insert_content' => 'string', 'bo_gallery_cols' => 'int', 'bo_gallery_width' => 'int', 'bo_gallery_height' => 'int', 'bo_mobile_gallery_width' => 'int', 'bo_mobile_gallery_height' => 'int', 'bo_upload_size' => 'int', 'bo_reply_order' => 'int', 'bo_use_search' => 'int', 'bo_order' => 'int', 'bo_count_write' => 'int', 'bo_count_comment' => 'int', 'bo_write_min' => 'int', 'bo_write_max' => 'int', 'bo_comment_min' => 'int', 'bo_comment_max' => 'int', 'bo_notice' => 'string', 'bo_upload_count' => 'int', 'bo_use_email' => 'int', 'bo_use_sns' => 'int', 'bo_use_captcha' => 'int', 'bo_sort_field' => 'string', 'bo_1_subj' => 'string', 'bo_2_subj' => 'string', 'bo_3_subj' => 'string', 'bo_4_subj' => 'string', 'bo_5_subj' => 'string', 'bo_6_subj' => 'string', 'bo_7_subj' => 'string', 'bo_8_subj' => 'string', 'bo_9_subj' => 'string', 'bo_10_subj' => 'string', 'bo_1' => 'string', 'bo_2' => 'string', 'bo_3' => 'string', 'bo_4' => 'string', 'bo_5' => 'string', 'bo_6' => 'string', 'bo_7' => 'string', 'bo_8' => 'string', 'bo_9' => 'string', 'bo_10' => 'string'
    ];

    /**
     * The attributes that should be mutated to dates.
     *
     * @var array
     */
    protected $dates = [
        
    ];

    /**
     * Indicates if the model should be timestamped.
     *
     * @var boolean
     */
    public $timestamps = false;

    // Scopes...

    // Functions ...

    // Relations ...
}
